#! /usr/bin/env bash


# Colors taken from https://github.com/dexpota/kitty-themes
bg_color="#323232"
selection_background="#5b5b5b"
selection_foreground="#ffffff"

black="#353535"
red="#d25252"
green="#a5c261"
yellow="#ffc66d"
blue="#6c99bb"
magenta="#d197d9"
cyan="#bed6ff"
white="#eeeeec"

bright_black="#535353"
bright_red="#f97394"
bright_green="#c2e075"
bright_yellow="#ffe48b"
bright_blue="#8ab7d9"
bright_magenta="#efb5f7"
bright_cyan="#dcf4ff"
bright_white="#ffffff"

light_grey="#808080"
dark_grey="#3a3a3a"
